var annotated_dup =
[
    [ "Article", "class_article.html", "class_article" ],
    [ "Article_manager", "class_article__manager.html", "class_article__manager" ],
    [ "Articles", "class_articles.html", "class_articles" ],
    [ "Comment", "class_comment.html", "class_comment" ],
    [ "Comment_manager", "class_comment__manager.html", "class_comment__manager" ],
    [ "Comments", "class_comments.html", "class_comments" ],
    [ "Dashboard", "class_dashboard.html", "class_dashboard" ],
    [ "Email", "class_email.html", "class_email" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "Event_manager", "class_event__manager.html", "class_event__manager" ],
    [ "Events", "class_events.html", "class_events" ],
    [ "Form", "class_form.html", "class_form" ],
    [ "Form_manager", "class_form__manager.html", "class_form__manager" ],
    [ "Forms", "class_forms.html", "class_forms" ],
    [ "Galerie", "class_galerie.html", "class_galerie" ],
    [ "Galerie_manager", "class_galerie__manager.html", "class_galerie__manager" ],
    [ "Galeries", "class_galeries.html", "class_galeries" ],
    [ "Message", "class_message.html", "class_message" ],
    [ "Message_manager", "class_message__manager.html", "class_message__manager" ],
    [ "Messages", "class_messages.html", "class_messages" ],
    [ "Newsletter", "class_newsletter.html", "class_newsletter" ],
    [ "Newsletter_manager", "class_newsletter__manager.html", "class_newsletter__manager" ],
    [ "Newsletters", "class_newsletters.html", "class_newsletters" ],
    [ "Pages", "class_pages.html", "class_pages" ],
    [ "properties", "classproperties.html", null ],
    [ "Subscription", "class_subscription.html", "class_subscription" ],
    [ "Subscription_manager", "class_subscription__manager.html", "class_subscription__manager" ],
    [ "User", "class_user.html", "class_user" ],
    [ "User_manager", "class_user__manager.html", "class_user__manager" ],
    [ "Users", "class_users.html", "class_users" ],
    [ "Welcome", "class_welcome.html", "class_welcome" ]
];